[package]
name = "convoy"
version = "0.1.0"
edition = "2021"

[features]
default = ["kafka"]
kafka = ["dep:rdkafka"]
avro = ["dep:schema_registry_converter", "dep:serde_avro_fast"]
opentelemetry = ["dep:opentelemetry", "dep:tracing-opentelemetry"]
unstable-features = []

[dependencies]
tokio = { version = "1", default-features = false, features = [
    "sync",
    "macros",
    "rt-multi-thread",
] }
async-trait = "0.1"
futures-lite = "1"
rand = "0.8"
serde = { version = "1", features = ["derive", "alloc"] }
serde_json = "1"
thiserror = "1"
tracing = { version = "0.1", features = ["log"] }
ahash = "0.8"
hex = "0.4"

# integrations
rdkafka = { version = "0.29.0", optional = true }
opentelemetry = { version = "0.25", optional = true }
tracing-opentelemetry = { version = "0.26", optional = true }

# integrations - avro
schema_registry_converter = { version = "4.0.0", optional = true }
serde_avro_fast = { version = "0.3.3", optional = true }

[dev-dependencies]
fake = { version = "2", features = ["derive"] }
opentelemetry = { version = "0.25", features = ["trace"] }
opentelemetry_sdk = { version = "0.25", features = ["trace"] }
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
httpmock = "0.6"

[[example]]
name = "kafka_consumer_default_handler"
path = "examples/kafka_consumer_default_handler.rs"
required-features = ["kafka"]

[[example]]
name = "kafka_produce_consume"
path = "examples/kafka_produce_consume.rs"
required-features = ["kafka"]

[[example]]
name = "kafka_produce_consume_avro"
path = "examples/kafka_produce_consume_avro.rs"
required-features = ["kafka", "avro"]
